version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes: 
      - cache:/data
  goapp:
    image: goapp:latest
    ports:
      - '8080:3000'
    depends_on:
      - cache
volumes:
  cache:
    driver: local