apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: vinidg/goapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
